<?php
$sql = "
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_reply` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
	  `weid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `uniacid` int(10) unsigned NOT NULL,
	  `title` varchar(50) NOT NULL COMMENT '规则标题',
	  `shareurl` varchar(255) NOT NULL COMMENT '活动网址',
	  `sharetitle` varchar(50) NOT NULL COMMENT '分享标题',
	  `sharecontent` varchar(100) NOT NULL COMMENT '分享简介',
	  `picture` varchar(225) NOT NULL COMMENT '规则图片',  
	  `sharephoto` varchar(225) NOT NULL COMMENT 'fx图片',  
	  `stopping` varchar(225) NOT NULL COMMENT 'fx图片',  
	  `nostart` varchar(225) NOT NULL COMMENT 'fx图片',
	  `end` varchar(225) NOT NULL COMMENT 'fx图片',  
	  `start_time` int unsigned NOT NULL COMMENT '开始时间',
	  `end_time` int unsigned NOT NULL COMMENT '结束时间',
	  `tstart_time` int unsigned NOT NULL COMMENT '投票开始时间',
	  `tend_time` int unsigned NOT NULL COMMENT '投票结束时间',
	  `bstart_time` int unsigned NOT NULL COMMENT '报名开始时间',
	  `bend_time` int unsigned NOT NULL COMMENT '报名结束时间',
	  `ttipstart` varchar(255) NOT NULL COMMENT '投票开始时间',
	  `ttipend` varchar(255) NOT NULL COMMENT '投票结束时间',
	  `btipstart` varchar(255) NOT NULL COMMENT '报名开始时间',
	  `btipend` varchar(255) NOT NULL COMMENT '报名结束时间',
	  `description` varchar(255) NOT NULL COMMENT '描述',
	  `command` varchar(255) NOT NULL COMMENT '命令',
	  `ckcommand` varchar(255) NOT NULL COMMENT '命令',
	  `content` text NOT NULL COMMENT '内容',
	  `tj` text NOT NULL COMMENT '站长统计代码',
	  `moshi` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '展示模式： 1 相册模式  2 详情模式',  
	  `status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '开关状态',
	  `addpv` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否开启添加投稿',  
	  `isbbsreply` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否开启评论',  
	  `cqtp` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否可重复投票',  
	  `tpsh` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '投稿是否需审核',  
	  `indexpx` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '活动首页显示,0 按最新排序 1 按人气排序 3 按投票数排序',  
	  `tpxz` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '投稿照片数限制',
	  `daytpxz` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '每日投票数限制',
	  `dayonetp` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '同一选手投票数限制',
	  `allonetp` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '同一选手最高投票数',
	  `fansmostvote` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '用户最高投票数',
	  `indextpxz` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '首页列表显示数',
	  `phbtpxz` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '人气榜显示个数',
	  `autolitpic` int(10) unsigned NOT NULL DEFAULT '50' COMMENT '裁剪大小',
	  `autozl` int(10) unsigned NOT NULL DEFAULT '50' COMMENT '裁剪质量',
	  `hits` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '点击量',
	  `xuninum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '虚拟人数',
	  `xuninumtime` int(10) unsigned NOT NULL DEFAULT '86400' COMMENT '虚拟间隔时间',
	  `xuninuminitial` int(10) unsigned NOT NULL DEFAULT '10' COMMENT '虚拟随机数值1',
	  `xuninumending` int(10) unsigned NOT NULL DEFAULT '50' COMMENT '虚拟随机数值2',
	  `xuninum_time` int(10) unsigned NOT NULL COMMENT '虚拟更新时间',
	  `isvisits` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否互访0为不可以1为可以',
	  `subscribe` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否强制需要关注公众号才能参与',
	  `opensubscribe` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否需要参与活动才算人气0为不需要1为需要',
	  `share_shownum` int(3) unsigned NOT NULL DEFAULT '10' COMMENT '加载一次显示多少参与者',
	  `userinfo` varchar(200) NOT NULL COMMENT '输入姓名或手机时的提示词',
	  `isindex` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否首页显示0为不需要1为需要',
	  `isvotexq` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否详情页显示0为不需要1为需要',
	  `ispaihang` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否排行页显示0为不需要1为需要',
	  `isreg` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否报名页显示0为不需要1为需要',
	  `isdes` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否描述页显示0为不需要1为需要',
	  `isrealname` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否需要输入姓名0为不需要1为需要',
	  `ismobile` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否需要输入手机号0为不需要1为需要',
	  `isweixin` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否需要输入微信号0为不需要1为需要',
	  `isqqhao` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否需要输入QQ号0为不需要1为需要',
	  `isemail` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否需要输入邮箱0为不需要1为需要',
	  `isaddress` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否需要输入地址0为不需要1为需要',
	  `isjob` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否需要输入职业0为不需要1为需要',
	  `isxingqu` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否需要输入兴趣0为不需要1为需要',
	  `isfans` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '0只保存本模块下1同步更新至官方FANS表',
	  `iscopyright` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0显示公众号版权1为显示自定义版权',
	  `copyrighturl` varchar(255) NOT NULL COMMENT '版权链接',
	  `copyright` varchar(50) NOT NULL COMMENT '版权',
	  `zbgcolor` varchar(50) NOT NULL COMMENT '背景色',
	  `zbg` varchar(255) NOT NULL COMMENT '背景图',
	  `zbgtj` varchar(255) NOT NULL COMMENT '背景图',
	  `lapiao` varchar(5) NOT NULL COMMENT '拉票',
	  `sharename` varchar(2) NOT NULL COMMENT '分享',
	  `ishuodong` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0',
      `mtemplates` varchar(500) NOT NULL COMMENT '模板ID',
      `huodong` varchar(500) NOT NULL COMMENT '活动',
	  `hhhdpicture` varchar(255) NOT NULL COMMENT '活动图片',
	  `messagetemplate` varchar(255) NOT NULL COMMENT '投票消息模板id 微信的模板id',
	  `regmessagetemplate` varchar(255) NOT NULL COMMENT '报名消息模板id 微信的模板id',
	  `shmessagetemplate` varchar(255) NOT NULL COMMENT '报名消息模板id 微信的模板id',
	  `addpvapp` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '前端是否允许用户报名',
	  `iscode` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否开启投票验证码',
	  `codekey` varchar(255) NOT NULL COMMENT '验证码key',
	  `isedes` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否开启首页显示说明',
	  `tmreply` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '弹幕评论是否同步到数据库',
	  `tmyushe` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '弹幕评论是否同步到数据库',
	  `isipv` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否开启IP作弊限制',
	  `ipturl` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '存在作弊ip后是否继续允许查看，投票，评论等',
	  `ipstopvote` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '存在作弊ip后是否继续允许查看，投票，评论等',
	  `ipannounce` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否开启公告',
	  `tmoshi` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '首页显示模式',
	  `mediatype` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '上传模式',
	  `mediatypem` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '上传模式',
	  `mediatypev` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '上传模式',
	  `bgarr` varchar(1000) NOT NULL COMMENT '颜色及背景配置',
	  `tpname` varchar(100) NOT NULL COMMENT '投票名称',
	  `rqname` varchar(100) NOT NULL COMMENT '人气名称',
	  `tpsname` varchar(100) NOT NULL COMMENT '投票数名称',
	  `votesuccess` varchar(200) NOT NULL COMMENT '投票成功提示语',
	  `subscribedes` varchar(200) NOT NULL COMMENT '分享提示语',
	  `csrs` varchar(10) NOT NULL COMMENT '参赛作品',
	  `ljtp` varchar(10) NOT NULL COMMENT '累计投票',
	  `cyrs` varchar(10) NOT NULL COMMENT '参与人数',
	  `voicebg` varchar(200) NOT NULL COMMENT '录音室背景',
	  `qiniu` varchar(600) NOT NULL COMMENT '七牛',
	  `voicemoshi` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '语音室模式',
	  `isdaojishi` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '倒计时',
	  `votetime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '用户投票时间',
	  `limitip` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '投票ip每天限制数',
	  `indexorder` int(3) unsigned NOT NULL DEFAULT '0' COMMENT '首页排序',
	  `ttipvote` varchar(100) NOT NULL COMMENT '用户投票时间结束提示语',
	  `webinfo` text NOT NULL COMMENT '内容',
	  `istopheader` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '最上方',
	  `zanzhums` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '赞助商显示',
      `istop` varchar(300) NOT NULL COMMENT '顶部设置',
      `isid` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT 'isid',
      `iplocallimit` varchar(100) NOT NULL COMMENT '地区限制',
      `iplocaldes` varchar(100) NOT NULL COMMENT '地区限制',
	  PRIMARY KEY (`id`),KEY `indx_uniacid` (`uniacid`),KEY `indx_rid` (`rid`)
	) ENGINE = MYISAM DEFAULT CHARSET = utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_provevote` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
	  `weid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `uniacid` int(10) unsigned NOT NULL,
	  `from_user` varchar(255) NOT NULL DEFAULT '' COMMENT '用户openid',
	  `tfrom_user` varchar(255) NOT NULL DEFAULT '' COMMENT '被投票用户openid',
	  `avatar` varchar(200) NOT NULL DEFAULT '' COMMENT '微信头像',  
	  `photo` varchar(200) NOT NULL DEFAULT '' COMMENT '照片',
	  `music` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `mediaid` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐id',
	  `timelength` varchar(200) NOT NULL DEFAULT '' COMMENT '时间轴',
	  `voice` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `vedio` varchar(200) NOT NULL DEFAULT '' COMMENT '视频',
	  `youkuurl` varchar(200) NOT NULL DEFAULT '' COMMENT '视频',
	  `fmmid` varchar(200) NOT NULL DEFAULT '' COMMENT '识别',
	  `picarr` varchar(2000) NOT NULL DEFAULT '' COMMENT '照片组',
	  `picarr_1` varchar(200) NOT NULL DEFAULT '' COMMENT '照片组',
	  `picarr_2` varchar(200) NOT NULL DEFAULT '' COMMENT '照片组',
	  `picarr_3` varchar(200) NOT NULL DEFAULT '' COMMENT '照片组',
	  `picarr_4` varchar(200) NOT NULL DEFAULT '' COMMENT '照片组',
	  `picarr_5` varchar(200) NOT NULL DEFAULT '' COMMENT '照片组',
	  `picarr_6` varchar(200) NOT NULL DEFAULT '' COMMENT '照片组',
	  `picarr_7` varchar(200) NOT NULL DEFAULT '' COMMENT '照片组',
	  `picarr_8` varchar(200) NOT NULL DEFAULT '' COMMENT '照片组',
	  `description` varchar(512) NOT NULL DEFAULT '' COMMENT '简介，描述',
	  `photoname` varchar(50) NOT NULL DEFAULT '' COMMENT '照片名字',
	  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
	  `realname` varchar(20) NOT NULL DEFAULT '' COMMENT '真实姓名',
	  `mobile` varchar(20) NOT NULL DEFAULT '' COMMENT '联系电话',
	  `job` varchar(20) NOT NULL DEFAULT '' COMMENT '职业',
	  `xingqu` varchar(20) NOT NULL DEFAULT '' COMMENT '兴趣',
	  `weixin` varchar(255) NOT NULL DEFAULT '' COMMENT '联系微信号',
	  `qqhao` varchar(20) NOT NULL DEFAULT '' COMMENT '联系QQ号码',
	  `email` varchar(255) NOT NULL DEFAULT '' COMMENT '联系邮箱',
	  `address` varchar(100) NOT NULL DEFAULT '' COMMENT '联系地址',
	  `photosnum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '票数',
	  `xnphotosnum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '虚拟票数',
	  `hits` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '人气',
	  `xnhits` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '虚拟人气',
	  `yaoqingnum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '邀请量',
	  `ewm` varchar(200) NOT NULL DEFAULT '' COMMENT '二维码地址',
	  `status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '审核状态',
	  `createip` varchar(50) NOT NULL DEFAULT '' COMMENT '创建IP',
	  `lastip` varchar(50) NOT NULL DEFAULT '' COMMENT '编辑IP',
	  `iparr` varchar(200) NOT NULL DEFAULT '' COMMENT 'ip地区',
	  `lasttime` int unsigned NOT NULL COMMENT '最后编辑时间',
	  `sharetime` int unsigned NOT NULL COMMENT '最后分享时间',
	  `sharenum` int unsigned NOT NULL COMMENT '最后分享',
	  `createtime` int unsigned NOT NULL COMMENT '注册时间',
	  `ysid` int(10) unsigned NOT NULL COMMENT 'ysid',
	  PRIMARY KEY (`id`),KEY `indx_uniacid` (`uniacid`),KEY `indx_createtime` (`createtime`),KEY `indx_from_user` (`from_user`),KEY `indx_rid` (`rid`)
	) ENGINE = MYISAM DEFAULT CHARSET = utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_provevote_name` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
	  `uniacid` int(10) unsigned NOT NULL,
	  `from_user` varchar(255) NOT NULL DEFAULT '' COMMENT '用户openid',
	  `musicname` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `photoname` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `picarr_1_name` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `picarr_2_name` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `picarr_3_name` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `picarr_4_name` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `picarr_5_name` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `picarr_6_name` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `picarr_7_name` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `picarr_8_name` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `musicnamefop` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `voicename` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `voicenamefop` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `vedioname` varchar(200) NOT NULL DEFAULT '' COMMENT '视频',
	  `vedionamefop` varchar(200) NOT NULL DEFAULT '' COMMENT '视频',
	  PRIMARY KEY (`id`),KEY `indx_uniacid` (`uniacid`),KEY `indx_rid` (`rid`),KEY `indx_from_user` (`from_user`)
	) ENGINE = MYISAM DEFAULT CHARSET = utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_provevote_voice` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
	  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `from_user` varchar(555) NOT NULL DEFAULT '' COMMENT 'openid',
	  `mediaid` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐id',
	  `timelength` varchar(200) NOT NULL DEFAULT '' COMMENT '时间轴',
	  `voice` varchar(200) NOT NULL DEFAULT '' COMMENT '音乐',
	  `fmmid` varchar(200) NOT NULL DEFAULT '' COMMENT '识别',
	  `ip` varchar(255) NOT NULL DEFAULT '' COMMENT 'IP',
	  `createtime` int(11) NOT NULL COMMENT '初始时间',
	  PRIMARY KEY (`id`),KEY `indx_uniacid` (`uniacid`),KEY `indx_createtime` (`createtime`),KEY `indx_from_user` (`from_user`),KEY `indx_rid` (`rid`)
	) ENGINE=MYISAM DEFAULT CHARSET=utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_votelog` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
	  `weid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `uniacid` int(10) unsigned NOT NULL,
	  `tptype` int(10) unsigned NOT NULL COMMENT '投票类型 1 微信页面投票  2 微信会话界面',
	  `from_user` varchar(255) NOT NULL DEFAULT '' COMMENT '用户openid',
	  `tfrom_user` varchar(255) NOT NULL DEFAULT '' COMMENT '被投票用户openid',
	  `afrom_user` varchar(255) NOT NULL DEFAULT '' COMMENT '分享用户openid',
	  `avatar` varchar(200) NOT NULL DEFAULT '' COMMENT '微信头像', 
	  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
	  `ip` varchar(50) NOT NULL DEFAULT '' COMMENT '投票IP',
	  `iparr` varchar(200) NOT NULL DEFAULT '' COMMENT 'ip地区',
	  `photosnum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '票数',
	  `createtime` int unsigned NOT NULL COMMENT '投票时间',
	  PRIMARY KEY (`id`),KEY `indx_uniacid` (`uniacid`),KEY `indx_rid` (`rid`),KEY `indx_createtime` (`createtime`),KEY `indx_from_user` (`from_user`)
	) ENGINE = MYISAM DEFAULT CHARSET = utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_bbsreply` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
	  `weid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `uniacid` int(10) unsigned NOT NULL,
	  `avatar` varchar(200) NOT NULL DEFAULT '' COMMENT '微信头像', 
	  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
	  `tid` varchar(125) NOT NULL COMMENT '帖子的ID',
	  `tfrom_user` varchar(255) NOT NULL DEFAULT '' COMMENT '帖子作者的openid',
	  `reply_id` varchar(125) NOT NULL COMMENT '回复评论帖子的ID',
	  `from_user` varchar(255) NOT NULL DEFAULT '' COMMENT '回复评论帖子的openid',
	  `to_reply_id` int(11) NOT NULL DEFAULT '0' COMMENT '回复评论的id',
	  `rfrom_user` varchar(255) NOT NULL DEFAULT '' COMMENT '被回复的评论的作者的openid',	  
	  `content` text NOT NULL COMMENT '评论回复内容',
	  `is_del` tinyint(2) DEFAULT '0' COMMENT '是否已删除 0-否 1-是',
	  `status` tinyint(2) DEFAULT '0' COMMENT '是否审核 0-否 1-是',
	  `storey` int(11) NOT NULL DEFAULT '0' COMMENT '绝对楼层',
	  `ip` varchar(255) NOT NULL DEFAULT '' COMMENT '回复IP',	
	  `iparr` varchar(200) NOT NULL DEFAULT '' COMMENT 'IP区域',
	  `createtime` int(11) NOT NULL COMMENT '回复时间',
	  PRIMARY KEY (`id`),KEY `indx_uniacid` (`uniacid`),KEY `indx_rid` (`rid`),KEY `indx_createtime` (`createtime`),KEY `indx_from_user` (`from_user`)
	) ENGINE=MYISAM DEFAULT CHARSET=utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_announce` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
	  `weid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `content` varchar(150) NOT NULL DEFAULT '' COMMENT '公告',
	  `nickname` varchar(100) NOT NULL DEFAULT '' COMMENT '公告',
	  `url` varchar(200) NOT NULL DEFAULT '' COMMENT '公告链接',
	  `createtime` int unsigned NOT NULL COMMENT '时间',
	  PRIMARY KEY (`id`),KEY `indx_uniacid` (`uniacid`),KEY `indx_createtime` (`createtime`)
	) ENGINE = MYISAM DEFAULT CHARSET = utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_iplist` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
	  `weid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `iparr` varchar(200) NOT NULL DEFAULT '' COMMENT 'IP区域',
	  `ipadd` varchar(100) NOT NULL DEFAULT '' COMMENT 'IP区域',
	  `createtime` int unsigned NOT NULL COMMENT '时间',
	  PRIMARY KEY (`id`),KEY `indx_uniacid` (`uniacid`),KEY `indx_rid` (`rid`),KEY `indx_createtime` (`createtime`)
	) ENGINE = MYISAM DEFAULT CHARSET = utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_iplistlog` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
	  `uniacid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `avatar` varchar(200) NOT NULL DEFAULT '' COMMENT '微信头像', 
	  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
	  `from_user` varchar(255) NOT NULL DEFAULT '' COMMENT 'openid',
	  `ip` varchar(255) NOT NULL DEFAULT '' COMMENT 'IP',
	  `hitym` varchar(255) NOT NULL DEFAULT '' COMMENT '点击页面',
	  `createtime` int(11) NOT NULL COMMENT '初始时间',
	  PRIMARY KEY (`id`),KEY `indx_uniacid` (`uniacid`),KEY `indx_rid` (`rid`),KEY `indx_createtime` (`createtime`),KEY `indx_from_user` (`from_user`)
	) ENGINE=MYISAM DEFAULT CHARSET=utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_gift` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
	  `uniacid` int(10) unsigned NOT NULL,  
	  `title` varchar(50) NOT NULL COMMENT '奖品名称',
	  `total` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '数量',
	  `total_winning` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '中奖数量',
	  `lingjiangtype` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '奖品库存减少方式0为有资格1为提交2为兑奖',
	  `description` text NOT NULL COMMENT '描述',
	  `inkind` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否是实物',
	  `activation_code` varchar(50) NOT NULL COMMENT '激活码',
	  `activation_url` varchar(215) NOT NULL COMMENT '激活地址',  
	  `break` int(3) unsigned NOT NULL DEFAULT '0' COMMENT '需要朋友人数',
	  `awardpic` varchar(200) NOT NULL COMMENT '奖品图片', 
	  `awardpass` varchar(20) NOT NULL COMMENT '兑奖密码',   
	  PRIMARY KEY (`id`),
	  KEY `indx_rid` (`rid`)
	) ENGINE = MYISAM DEFAULT CHARSET = utf8;
	CREATE TABLE if not exists `ims_fm_photosvote_banners` (
	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `weid` int(11) default 0,
	  `uniacid` int(10) unsigned NOT NULL,
	  `rid` int(11) default 0,
	  `bannername` varchar(50) DEFAULT '',
	  `link` varchar(255) DEFAULT '',
	  `thumb` varchar(255) DEFAULT '',
	  `displayorder` int(11) DEFAULT '0',
	  `enabled` int(11) DEFAULT '0',
	  PRIMARY KEY (`id`),KEY `indx_weid` (`weid`),KEY `indx_enabled` (`enabled`),KEY `indx_displayorder` (`displayorder`)
	) ENGINE=MyISAM DEFAULT CHARSET=utf8;
	CREATE TABLE if not exists `ims_fm_photosvote_advs` (
	  `id` int(11) NOT NULL AUTO_INCREMENT,
	  `weid` int(11) default 0,
	  `uniacid` int(10) unsigned NOT NULL,
	  `rid` int(11) default 0,
	  `advname` varchar(50) DEFAULT '',
	  `description` varchar(350) DEFAULT '',
	  `link` varchar(255) DEFAULT '',
	  `thumb` varchar(255) DEFAULT '',
	  `displayorder` int(11) DEFAULT '0',
	  `times` int(11) DEFAULT '0',
	  `ismiaoxian` int(2) DEFAULT '0',
	  `issuiji` int(2) DEFAULT '0',
	  `nexttime` int(11) DEFAULT '0',
	  `enabled` int(11) DEFAULT '0',
	  PRIMARY KEY (`id`),KEY `indx_weid` (`weid`),KEY `indx_enabled` (`enabled`),KEY `indx_displayorder` (`displayorder`)
	) ENGINE=MyISAM DEFAULT CHARSET=utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_awarding` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `weid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `uniacid` int(10) unsigned NOT NULL,
	  `typeid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '区域ID',
	  `shoptitle` varchar(50) NOT NULL DEFAULT '' COMMENT '兑奖店面名称',
	  `address` varchar(200) NOT NULL DEFAULT '' COMMENT '兑奖地址',
	  `tel` varchar(50) NOT NULL DEFAULT '' COMMENT '联系电话',
	  `pass` varchar(20) NOT NULL DEFAULT '' COMMENT '兑奖密码',
	  `images` varchar(200) NOT NULL DEFAULT '' COMMENT '广告或店面图',
	  `carmap` varchar(50) NOT NULL COMMENT '地图导航',
	  PRIMARY KEY (`id`)
	) ENGINE = MYISAM DEFAULT CHARSET = utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_awardingtype` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `weid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `uniacid` int(10) unsigned NOT NULL,
	  `quyutitle` varchar(50) NOT NULL DEFAULT '' COMMENT '分类名称',
	  `orderid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '排序',
	  PRIMARY KEY (`id`)
	) ENGINE = MYISAM DEFAULT CHARSET = utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_giftmika` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
	  `uniacid` int(10) unsigned NOT NULL,
	  `giftid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '礼盒ID', 
	  `from_user` varchar(50) NOT NULL DEFAULT '' COMMENT '用户openid',  
	  `mika` varchar(50) NOT NULL COMMENT '密卡字符串',
	  `activationurl` varchar(200) NOT NULL COMMENT '激活地址',
	  `typename` varchar(20) NOT NULL DEFAULT '' COMMENT '类型说明',
	  `description` varchar(50) NOT NULL DEFAULT '' COMMENT '描述',
	  `status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否领取1为领取过',
	  PRIMARY KEY (`id`),
	  KEY `indx_rid` (`rid`)
	) ENGINE = MYISAM DEFAULT CHARSET = utf8;
	CREATE TABLE IF NOT EXISTS `ims_fm_photosvote_data` (
	  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
	  `weid` int(10) unsigned NOT NULL COMMENT '公众号ID',
	  `uniacid` int(10) unsigned NOT NULL,
	  `fromuser` varchar(150) NOT NULL DEFAULT '' COMMENT '分享用户openid',
	  `from_user` varchar(150) NOT NULL DEFAULT '' COMMENT '当前用户openid',
	  `tfrom_user` varchar(150) NOT NULL DEFAULT '' COMMENT '被分享用户openid',
	  `avatar` varchar(200) NOT NULL DEFAULT '' COMMENT '微信头像',
	  `nickname` varchar(50) NOT NULL DEFAULT '' COMMENT '微信昵称',
	  `rid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '规则id',
	  `uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '分享人UID',
	  `isin` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否参与',
	  `visitorsip` varchar(15) NOT NULL DEFAULT '' COMMENT '访问IP',
	  `visitorstime` int unsigned NOT NULL COMMENT '访问时间',
	  `viewnum` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '查看次数',
	  PRIMARY KEY (`id`),KEY `indx_uniacid` (`uniacid`),KEY `indx_rid` (`rid`),KEY `indx_uid` (`uid`),KEY `indx_from_user` (`from_user`)
	) ENGINE = MYISAM DEFAULT CHARSET = utf8;	
";
pdo_run($sql);